# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5dfaa7928006325a3a0e61d9e4ee51595e1e9b05a3e3e9307c6f3f9dd5ae82668d2005707c9c5db0f9443caf4a89a7d48db7c007015e3a6d95dd742c8684bcf
  spotify_id: <%= ENV["SPOTIFY_ID"]%>
  spotify_client: <%= ENV["SPOTIFY_CLIENT"]%>

test:
  secret_key_base: 774085539d192fd73bd60489b90011d2c56a153907e7c2aad6e22a366188949353b478908600429dbfc65f9d73b15476a04a03335f73f3250424159c20a4ba45
  spotify_id: <%= ENV["SPOTIFY_ID"]%>
  spotify_client: <%= ENV["SPOTIFY_CLIENT"]%>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  spotify_id: <%= ENV["SPOTIFY_ID"]%>
  spotify_client: <%= ENV["SPOTIFY_CLIENT"]%>
